# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # https://github.com/nuxt/nuxt.js/actions/runs/134324621/workflow#L39
  setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: checkout
        uses: actions/checkout@v2

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-v12-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: node-v12-gobanyo-${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: node-v12-gobanyo-${{ github.sha }}

      - name: lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12 

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: node-v12-gobanyo-${{ github.sha }}

      - name: test
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: node-v12-gobanyo-${{ github.sha }}

      - name: build
        run: yarn build

